import { LayoutItem } from '../../model/layout-item.model';

export interface AuthData extends LayoutItem {
  route: string;
}

export const data: AuthData[] = [
  {
    Name: '凤尾鱼',
    EnglishName: 'anchovy',
    Sell: 200,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 4201,
    IconFilename: require('../../images/Fish/Fish81.png'),
    CritterpediaFilename: 'FishAntyobi',
    FurnitureFilename: 'FtrFishAntyobi',
    Description: 'There are more than 140 species of anchovy, but they do all have some things in common. They are small and feed by simply swimming with their mouths open to filter food particles from the sea. (In my sleepier moments, I sometimes wish I could do that...)',
    Color1: 'Blue',
    Color2: 'Red',
    route: 'Article1'
  },
  {
    Name: '神仙鱼',
    EnglishName: 'angelfish',
    Sell: 3000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2247,
    IconFilename: require('../../images/Fish/Fish30.png'),
    CritterpediaFilename: 'FishAngelfish',
    FurnitureFilename: 'FtrFishAngelfish',
    Description: 'The angelfish is truly a beautiful creature. Just look at the elegance of those fins!Despite the name, however, these lovelies are known to be rather aggressive. They\'ve no qualms about relentlessly pursuing fish much smaller than themselves! Why, they even attack their own kin! It seems no fish is safe around these "angelic" bullies. It makes one wonder who comes up with these names. Appearances— and names— can be deceiving.',
    Color1: 'Yellow',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '巨骨舌鱼',
    EnglishName: 'arapaima',
    Sell: 10000,
    HHABasePoints: 71,
    Size: '3x2',
    InternalID: 2253,
    IconFilename: require('../../images/Fish/Fish36.png'),
    CritterpediaFilename: 'FishPiraruku',
    FurnitureFilename: 'FtrFishPiraruku',
    Description: 'The stately arapaima is quite large. Indeed, it is among the largest freshwater fish there are. Furthermore, these fascinating fish make quite the family unit. That is to say, male arapaimas protect their young by holding them gently in their mouths. Meanwhile, female arapaimas swim circles around these full-mouthed fathers fending off predators. It simply goes to show that cold-blooded creatures can be heartwarming too.',
    Color1: 'Black',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '骨舌鱼',
    EnglishName: 'arowana',
    Sell: 10000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2250,
    IconFilename: require('../../images/Fish/Fish33.png'),
    CritterpediaFilename: 'FishArowana',
    FurnitureFilename: 'FtrFishArowana',
    Description: 'It would seem your angling expertise knows no bounds! This beauteous arowana fetches a pretty Bell, though I\'d venture to say that its true price is beyond measure. The arowana has been on the endangered-species list for some time. It\'s up to us to remain educated and do all we can to help preserve such magnificent creatures. Not to worry, old bean. This lovely fishy friend is in good wings here! On behalf of the museum, I thank you warmly for your unending generosity!',
    Color1: 'Yellow',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '条石鲷',
    EnglishName: 'barred knifejaw',
    Sell: 5000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2265,
    IconFilename: require('../../images/Fish/Fish47.png'),
    CritterpediaFilename: 'FishIshidai',
    FurnitureFilename: 'FtrFishIshidai',
    Description: 'Wonderful! I would love nothing more! The barred knifejaw, also called the striped beakfish, is a lovely fish with a distinctive striped pattern. It is reportedly also a very curious fish in that it has been known to approach swimmers to "greet" them. They also tend to be good at avoiding fishing hooks, so well done on outwitting this one!',
    Color1: 'White',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '太平洋桶眼鱼',
    EnglishName: 'barreleye',
    Sell: 15000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 4204,
    IconFilename: require('../../images/Fish/Fish84.png'),
    CritterpediaFilename: 'FishDemenigisu',
    FurnitureFilename: 'FtrFishDemenigisu',
    Description: 'The barreleye is a deep-sea fish with protuberant eyes and a clear head, so some of its organs are... visible. At first blush, a transparent head seems absurd, but there is a reason: so it can see things directly above! But I must confess - the more I learn about deep-sea fish, the happier I am to live on dry land, wot.',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '斗鱼',
    EnglishName: 'betta',
    Sell: 2500,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 4191,
    IconFilename: require('../../images/Fish/Fish77.png'),
    CritterpediaFilename: 'FishBeta',
    FurnitureFilename: 'FtrFishBeta',
    Description: 'The betta has long fins and beautiful coloring. It is a tropical fish popular in decorative aquariums. They\'re very territorial and will fight to complete exhaustion, so aquarists must keep them carefully. Rarely do such beauty and violence commingle outside the rowdiest of sunset-viewing parties.',
    Color1: 'Light blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '红目鲫',
    EnglishName: 'bitterling',
    Sell: 900,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2215,
    IconFilename: require('../../images/Fish/Fish0.png'),
    CritterpediaFilename: 'FishTanago',
    FurnitureFilename: 'FtrFishTanago',
    Description: 'Bitterlings hide their eggs inside large bivalves—like clams—where the young can stay safe until grown. The bitterling isn\'t being sneaky. No, their young help keep the bivalve healthy by eating invading parasites! It\'s a wonderful bit of evolutionary deal making, don\'t you think? Each one keeping the other safe... Though eating parasites does not sound like a happy childhood... Is that why the fish is so bitter?',
    Color1: 'Light blue',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '黑鲈鱼',
    EnglishName: 'black bass',
    Sell: 400,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2234,
    IconFilename: require('../../images/Fish/Fish19.png'),
    CritterpediaFilename: 'FishBlackbass',
    FurnitureFilename: 'FtrFishBlackbass',
    Description: 'The black bass is a formidably strong fish and, as such, is a common target for sport anglers. In some areas, there are even those who professionally catch just black bass! Yet in other areas where they are NOT native, they are considered an ecological nuisance. Invasive, even. One cannot help but wonder who is to blame for their invasion, hoo.',
    Color1: 'Green',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '河豚',
    EnglishName: 'blowfish',
    Sell: 5000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2262,
    IconFilename: require('../../images/Fish/Fish73.png'),
    CritterpediaFilename: 'FishFugu',
    FurnitureFilename: 'FtrFishFugu',
    Description: 'As you may know, blowfish carry a deadly poison and are among the most toxic creatures on earth. What you may not have known is that poison and spines are not the limit of this animal\'s defenses! A predator that tries to swallow a blowfish before it inflates can find itself quickly choking. To be honest, if said predator can get past poison, spines, AND choking hazards, I feel they\'ve earned a meal.',
    Color1: 'Beige',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '旗鱼',
    EnglishName: 'blue marlin',
    Sell: 10000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2275,
    IconFilename: require('../../images/Fish/Fish58.png'),
    CritterpediaFilename: 'FishKajiki',
    FurnitureFilename: 'FtrFishKajiki',
    Description: 'The blue marlin has a distinctive angular shape and no scales. It is an unusual relative of the tuna. These mighty fish can exceed 13 feet from bill to tail. Some accounts even have it fighting with whales! No wonder it\'s a popular target for sport fishing: unlike most fish, it seems like a worthy opponent.',
    Color1: 'Blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '蓝腮太阳鱼',
    EnglishName: 'bluegill',
    Sell: 180,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2232,
    IconFilename: require('../../images/Fish/Fish17.png'),
    CritterpediaFilename: 'FishBlueguill',
    FurnitureFilename: 'FtrFishBlueguill',
    Description: 'The bluegill is incredibly common. A bit too common, depending upon where you are. They eat anything that fits in their mouths and are highly adaptable. The bane of fishermen in some areas, bluegill is often the only fish to be caught! But looking in its wee beady eyes, I must say I see no ill will in it...',
    Color1: 'Blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '耳带蝴蝶鱼',
    EnglishName: 'butterfly fish',
    Sell: 1000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2259,
    IconFilename: require('../../images/Fish/Fish42.png'),
    CritterpediaFilename: 'FishChouchouuo',
    FurnitureFilename: 'FtrFishChouchouuo',
    Description: 'Ah, the butterfly fish is just charming with its beautiful colors and elegant movements. I refer to it as a butterfly fish, but it\'s actually a grouping in which there are over 100 types! These beautiful aquatic friends swim in schools amid coral, fluttering back and forth with the tides. The sheer awe one must experience when witnessing such a sight. It must be a dream! So much better than actual butterflies...',
    Color1: 'Yellow',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲤鱼',
    EnglishName: 'carp',
    Sell: 300,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2219,
    IconFilename: require('../../images/Fish/Fish5.png'),
    CritterpediaFilename: 'FishKoi',
    FurnitureFilename: 'FtrFishKoi',
    Description: 'Oh, the carp... have you ever seen their teeth? For your sake, I hope you have not! Carp have teeth in their throat strong enough to crunch on hard things like shells and fingers! A good rule of thumb when dealing with other species is to keep your fingers out of their mouths. Although, having neither thumbs nor fingers, I am quite safe from this little fellow!',
    Color1: 'Gray',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲶鱼',
    EnglishName: 'catfish',
    Sell: 800,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2229,
    IconFilename: require('../../images/Fish/Fish14.png'),
    CritterpediaFilename: 'FishNamazu',
    FurnitureFilename: 'FtrFishNamazu',
    Description: 'Catfish don\'t have scales and are rather slimy. Believe it or not, this slime helps them breathe! Some species of catfish are nocturnal, and they\'ll feed on almost anything. They use a suctioning action to pull in their food. Did I mention they can grow as large as you or I?',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '花羔红点鲑',
    EnglishName: 'char',
    Sell: 3800,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2239,
    IconFilename: require('../../images/Fish/Fish24.png'),
    CritterpediaFilename: 'FishOoiwana',
    FurnitureFilename: 'FtrFishOoiwana',
    Description: 'The char is one of the bigger first around the world, and, in the world of fish, that\'s quite an accomplishment! They are territorial predators, and therefore must constantly defend their \'turf\' from others. So when you see a large char like this one, it is likely a skilled fighter and veteran of many battles. My feathers! I hope it never has cause to go into battle with me!',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '樱花钩吻鲑',
    EnglishName: 'cherry salmon',
    Sell: 1000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2238,
    IconFilename: require('../../images/Fish/Fish23.png'),
    CritterpediaFilename: 'FishYamame',
    FurnitureFilename: 'FtrFishYamame',
    Description: 'The cherry salmon is related to the salmon, and is known for its distinctive pattern of "polka dots". There polka dots disappear as they mature, but ONLY in the first of certain geographic regions. Pity the poor researchers that must make sense of the cherry salmon\'s fickle fashion sense.',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '小丑鱼',
    EnglishName: 'clown fish',
    Sell: 650,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2257,
    IconFilename: require('../../images/Fish/Fish40.png'),
    CritterpediaFilename: 'FishKumanomi',
    FurnitureFilename: 'FtrFishKumanomi',
    Description: 'Few can deny the delightful qualities of the clown fish. These vibrant fishes make their home among venomous anemones. It\'s a mutually beneficial arrangement. The clown fish finds safety in the anemone\'s wriggling arms, as well as leftover scraps of food. In return, clown fish ward off parasites and predators for the anemone. Thus these colorful fish remind us of the importance of maintaining good cheer among our roommates.',
    Color1: 'Orange',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '矛尾鱼',
    EnglishName: 'coelacanth',
    Sell: 15000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2284,
    IconFilename: require('../../images/Fish/Fish63.png'),
    CritterpediaFilename: 'FishSirakansu',
    FurnitureFilename: 'FtrFishSirakansu',
    Description: 'The coelacanth is a deep-sea fish that has been around since the age of the dinosaurs. They were long thought extinct, so when living specimens were discovered, it was quite a shock! Now I\'ll just have to figure out where in the museum to display it— fish or fossils!',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '淡水龙虾',
    EnglishName: 'crawfish',
    Sell: 200,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2223,
    IconFilename: require('../../images/Fish/Fish10.png'),
    CritterpediaFilename: 'FishZarigani',
    FurnitureFilename: 'FtrFishZarigani',
    Description: 'Ohoo! So you have found a crawfish. Neither crab nor lobster, crawfish evolved in an interesting manner. Beware their fearsome pinchy pinchers! Behold their many legs! I say! It is a big bug-like, eh wot...The more I look at it, the more unsettled I feel... Let\'s be done with this and never speak of it again, shall we?',
    Color1: 'Red',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲫鱼',
    EnglishName: 'crucian carp',
    Sell: 160,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 328,
    IconFilename: require('../../images/Fish/Fish2.png'),
    CritterpediaFilename: 'FishFuna',
    FurnitureFilename: 'FtrFishFuna',
    Description: 'I wonder... Do you know how to tell the difference between a crucian carp and a standard-issue carp? It\'s quite easy to tell the two apart... One must simply locate the barbels. Or, rather, the lack of them! And just what is a barbel, you ask? Well, a barbel looks a little something like a mustache. A run-of-the-mill carp will sport this unsightly "facial hair," while a crucian carp is considerably better groomed! I tried to grow a mustache when I was younger. It never did fill in quite right... All for the best in the end, as mustaches go so much better with noses than with beaks!',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲽鱼',
    EnglishName: 'dab',
    Sell: 300,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2268,
    IconFilename: require('../../images/Fish/Fish50.png'),
    CritterpediaFilename: 'FishKarei',
    FurnitureFilename: 'FtrFishKarei',
    Description: 'The dab is a flatfish that bears some resemblance to the olive flounder, though their mouths are different. Personally, I am morbidly fascinated by each fish\'s eye placement. The dab\'s eyes are both on its right side, while the olive flounder\'s are on the left. These fish spend lots of time lying on their sides in the sand, so the odd eye placement makes some sense... But its-how can I put this? Creepy? Viscerally disturbing? Profoundly upsetting to fans of symmetry?',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '雅罗鱼',
    EnglishName: 'dace',
    Sell: 240,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2217,
    IconFilename: require('../../images/Fish/Fish3.png'),
    CritterpediaFilename: 'FishUgui',
    FurnitureFilename: 'FtrFishUgui',
    Description: 'Dace are shiny little fish that enjoy freshwater streams with gravelly bottoms and plenty of sunlight. What a fishy paradise...until the larger fish move in and begin eating the dace! Sadly, the shiny dace are easy for other fish to spot, which makes them a popular snack. However, this particular specimen here has no need to worry. There\'s a strict "No Eating Your Neighbor" policy at this institution.',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '黄金河虎',
    EnglishName: 'dorado',
    Sell: 15000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2251,
    IconFilename: require('../../images/Fish/Fish34.png'),
    CritterpediaFilename: 'FishDolado',
    FurnitureFilename: 'FtrFishDolado',
    Description: 'Woo-hoo! So shiny! This massive fish\'s name, dorado, means "golden" in Spanish— a fitting title. They are also quite valuable, I understand. I congratulate you on your top-notch angling! They are rather large, eh wot? It makes one wonder what all they might feed on... Fowl, perhaps?! One quivers at the very thought! Well, it\'ll be safe behind glass, no doubt. Quite safe, hoo',
    Color1: 'Yellow',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '灯笼鱼',
    EnglishName: 'football fish',
    Sell: 2500,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2273,
    IconFilename: require('../../images/Fish/Fish56.png'),
    CritterpediaFilename: 'FishChouchinankou',
    FurnitureFilename: 'FtrFishChouchinankou',
    Description: 'The football fish is a strange and grotesque deep-sea fish with a lantern-like light on its forehead. Its light is apparently powered by luminous bacteria and other glowing microorganisms. One theory says it can spray these luminescent sidekicks when prey approaches in order to dazzle them...The deep contains many mysteries...as well as some things that are just sort of odd and off-putting.',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '塘鳢鱼',
    EnglishName: 'freshwater goby',
    Sell: 400,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2227,
    IconFilename: require('../../images/Fish/Fish12.png'),
    CritterpediaFilename: 'FishDonko',
    FurnitureFilename: 'FtrFishDonko',
    Description: 'The freshwater goby is an unassuming specimen. But beneath that calm, fish exterior, true gluttony resides! It will eat anything that will fit in its mouth...And its mouth is quite the gaping maw, so I recommend you refrain from drawing attention to yourself!',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '青蛙',
    EnglishName: 'frog',
    Sell: 120,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2226,
    IconFilename: require('../../images/Fish/Fish11.png'),
    CritterpediaFilename: 'FishKaeru',
    FurnitureFilename: 'FtrFishKaeru',
    Description: 'I understand that frogs converse with fellow frogs through a number of varied calls, as it were. Ribbit! My prince has arrived! Gribbit riiibbit! This pond is tragic! Ribbity rib\'t! I think you\'re splendid! Hoo hoo, of course I have no clue what they\'re saying, but I like to think if I practice enough, I might!',
    Color1: 'Green',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '雀鳝',
    EnglishName: 'gar',
    Sell: 6000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2252,
    IconFilename: require('../../images/Fish/Fish35.png'),
    CritterpediaFilename: 'FishGa',
    FurnitureFilename: 'FtrFishGa',
    Description: 'Hoo hoo! So you have snagged a gar. Did you know this beastly fish can grow up to nine feet long? Indeed, the gar is a remnant of times long past— a living fossil, if you will. It not only has sharp teeth and armor-like scalesn, it has the ability to take breaths of air as well! Ah, to look upon this unusual fish is to get a glimpse of our prehistoric past.',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '黑鱼',
    EnglishName: 'giant snakehead',
    Sell: 5500,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2231,
    IconFilename: require('../../images/Fish/Fish16.png'),
    CritterpediaFilename: 'FishRaigyo',
    FurnitureFilename: 'FtrFishRaigyo',
    Description: 'The giant snakehead is quite a sight to behold, wot! One glance conjurs up visions of its namesake. This resilient creature can even find a home in the mud, where it is able to breathe. As a matter of fact, it dislikes cold weather, so during wintertime the mud serves as its temporary home. I hear that they eat anything that swims past their head. While odd, I feel a sense of owlship with them.',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '白面弄鱼',
    EnglishName: 'giant trevally',
    Sell: 4500,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2276,
    IconFilename: require('../../images/Fish/Fish70.png'),
    CritterpediaFilename: 'FishRouninaji',
    FurnitureFilename: 'FtrFishGT',
    Description: 'The giant trevally, as befits its name, can reach six feet in length and 180 pounds! Its size and strength have made it a favored opponent for anglers since time immemorial. They are also ingenious hunters, sometimes taking advantage of other predators to distract their prey. There have even been documented cases of them attacking —gulp— birds.',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '金鳟',
    EnglishName: 'golden trout',
    Sell: 15000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 4193,
    IconFilename: require('../../images/Fish/Fish79.png'),
    CritterpediaFilename: 'FishGoldenTorauto',
    FurnitureFilename: 'FtrFishGoldenTorauto',
    Description: 'The golden trout is a beautifully colored fish that can only live in very clean waters. They are difficult to come across since they are found only in high mountain streams. As a side note, I find it much easier to appreciate fish that aren\'t such prima donnas about everything.',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '金鱼',
    EnglishName: 'goldfish',
    Sell: 1300,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 329,
    IconFilename: require('../../images/Fish/Fish7.png'),
    CritterpediaFilename: 'FishKingyo',
    FurnitureFilename: 'FtrFishKingyo',
    Description: 'Goldfish are so cute and delicate... but do you know how big they can get? Why, they can grow up to... a foot in length! Well, sometimes. The size of the tank they\'re kept in tends to restrict their growth. And just how big will this goldfish get in our large museum tank? I look forward to finding out!',
    Color1: 'Red',
    Color2: 'Light blue',
    route: 'Article1'
  },
  {
    Name: '鲨鱼',
    EnglishName: 'great white shark',
    Sell: 15000,
    HHABasePoints: 71,
    Size: '3x2',
    InternalID: 2280,
    IconFilename: require('../../images/Fish/Fish62.png'),
    CritterpediaFilename: 'FishSame',
    FurnitureFilename: 'FtrFishSame',
    Description: 'Great white sharks are obviously known first and foremost for their biting. They are masters of the craft! They do lose teeth regularly through biting-related activities, but, luckily, those teeth grow back quickly. In fact, their missing teeth can be regrown in a single day. Just imagine their tooth-fairy-related income!',
    Color1: 'Blue',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '孔雀鱼',
    EnglishName: 'guppy',
    Sell: 1300,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2245,
    IconFilename: require('../../images/Fish/Fish29.png'),
    CritterpediaFilename: 'FishGuppi',
    FurnitureFilename: 'FtrFishGuppi',
    Description: 'Oh my! Would you look at that! Such a beautiful, snazzy little fellow that guppy is! The shape and coloration of guppy fins are all unique. Quite eye-catching, I must say. Do you imagine they host contests for "most snazzy"? And...do you suppose I might receive an invite?',
    Color1: 'Blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '双髻鲨',
    EnglishName: 'hammerhead shark',
    Sell: 8000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2279,
    IconFilename: require('../../images/Fish/Fish61.png'),
    CritterpediaFilename: 'FishShumokuzame',
    FurnitureFilename: 'FtrFishShumokuzame',
    Description: 'The hammerhead shark is known for its distinctive, hammer-shaped head, hence the name. Er, obviously. Anyhoot, this oddly shaped head allows the beast to see 360 degrees around itself, from top to bottom. Imagine being able to see so widely! You could check for untied shoelaces AND imminent rain simultaneously!',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '竹荚鱼',
    EnglishName: 'horse mackerel',
    Sell: 150,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2264,
    IconFilename: require('../../images/Fish/Fish46.png'),
    CritterpediaFilename: 'FishAji',
    FurnitureFilename: 'FtrFishAji',
    Description: 'Supposedly the horse mackerel derives its name from a-false-myth about its strengh as a swimmer. The gist of it is that these fish are so powerful underwater that smaller fish can ride them as steeds! It\'s absurd, of course. Where would these alleged fish jockeys attach a saddle, much less horseshoes? One does wish that people would construct their legends with a BIT more scientific plausibility!',
    Color1: 'Blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '稻田鱼',
    EnglishName: 'killifish',
    Sell: 300,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2222,
    IconFilename: require('../../images/Fish/Fish9.png'),
    CritterpediaFilename: 'FishMedaka',
    FurnitureFilename: 'FtrFishMedaka',
    Description: 'Ah, the magnificent killifish! Did you know there are over 1,000 different species? My own favorite killifish species are the mangrove, which can live on land for weeks, breathing air! And the mummichog, the first fish ever brought to space. I wonder if the killifish you\'ve brought me is related to either those intrepid explorers?',
    Color1: 'Yellow',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '帝王鲑',
    EnglishName: 'king salmon',
    Sell: 1800,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2243,
    IconFilename: require('../../images/Fish/Fish28.png'),
    CritterpediaFilename: 'FishKingsalmon',
    FurnitureFilename: 'FtrFishKingsalmon',
    Description: 'The king salmon didn\'t get its name for nothing.This stately fish can weigh in at up to 130 pounds! It\'s clear why it\'s referred to as the king of salmon. I imagine even the mightiest net can catch no more than a few at a time.I must say it\'s a miracle to me that you didn\'t get dragged out to sea by this one, wot!',
    Color1: 'Gray',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '锦鲤',
    EnglishName: 'koi',
    Sell: 4000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2220,
    IconFilename: require('../../images/Fish/Fish6.png'),
    CritterpediaFilename: 'FishNishikigoi',
    FurnitureFilename: 'FtrFishNishikigoi',
    Description: 'Koi are a variety of carp bred for their color mutations...starting more than a thousand years ago! Well, one glance at their impressive coloring tells you that the centuries of effort were worth it. And even today people still selectively breed koi in search of new color combinations! One marvels at the thought of what the koi may look like in another thousand years.',
    Color1: 'Red',
    Color2: 'White',
    route: 'Article1'
  },
  {
    Name: '泥鳅',
    EnglishName: 'loach',
    Sell: 400,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2228,
    IconFilename: require('../../images/Fish/Fish13.png'),
    CritterpediaFilename: 'FishDojou',
    FurnitureFilename: 'FtrFishDojou',
    Description: 'Loaches are a large group of bottom-feeding freshwater fish. Because there are so many species, it is difficult to generalize about them all. The one thing they all have in common is perhaps their most unappealing trait; the name \'loach.\' Repellent, isn\'t it? They should have just called it the \'cockloach\' and been done with it, eh wot! Loach...loach... It just tastes terrible in the beak.',
    Color1: 'Brown',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '鬼头刀',
    EnglishName: 'mahi-mahi',
    Sell: 6000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 4202,
    IconFilename: require('../../images/Fish/Fish82.png'),
    CritterpediaFilename: 'FishShiira',
    FurnitureFilename: 'FtrFishShiira',
    Description: 'The mahi-mahi is an ocean fish known for its wide, somewhat-cute face. It can reach over six feet long. It is known by different names including "dolphinfish," even though it has no relation to dolphins. They live in only in warm, tropical waters...which perhaps explains the relaxed, happy look on their faces.',
    Color1: 'Yellow',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '中华绒螯蟹',
    EnglishName: 'mitten crab',
    Sell: 2000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2244,
    IconFilename: require('../../images/Fish/Fish66.png'),
    CritterpediaFilename: 'FishSyanhaigani',
    FurnitureFilename: 'FtrFishShanghai',
    Description: 'The mitten crab was named for its impossibly adorable and fuzzy little pincers. These cute crustaceans embark on quite the journey. They\'re first born in brackish waters. Then they mature in freshwater. Finally, they travel to the ocean to create more mitten crabs!Hoo! How I delight in the thought of thousands of tiny mittened crabs scuttling about!',
    Color1: 'Black',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '裸胸鳝',
    EnglishName: 'moray eel',
    Sell: 2000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2271,
    IconFilename: require('../../images/Fish/Fish55.png'),
    CritterpediaFilename: 'FishUtsubo',
    FurnitureFilename: 'FtrFishUtsubo',
    Description: 'Despite its rather frightening features, the moray eel is really a very cowardly fish. It lives its life hiding in caves, and will only attack if you\'re looking for a fight. You\'ve heard of a "bark that is worse than the bite"? Well, the moray eel has a face that\'s worse than its fight!',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: 'Napoleonfish',
    Sell: 10000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2260,
    IconFilename: require('../../images/Fish/Fish43.png'),
    CritterpediaFilename: 'FishNaporeonfish',
    FurnitureFilename: 'FtrFishNaporeonfish',
    Description: 'Quite the catch you\'ve brought! The stately and debonair Napoleonfish is truly something to behold. Those beady eyes! That bumpy head! That bold blue-green coloring! Alas, this quirky creature is quite endangered due to a variety of factors. Needless to say, we must do our very best to take care of our lumpy friend and its environment.',
    Color1: 'Light blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '霓虹灯鱼',
    EnglishName: 'neon tetra',
    Sell: 500,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2248,
    IconFilename: require('../../images/Fish/Fish31.png'),
    CritterpediaFilename: 'FishNeontetora',
    FurnitureFilename: 'FtrFishNeontetora',
    Description: 'Hoo! Wonderful! The neon tetra is truly a marvel of the tropical-fish world. Just look at how tiny it is! And how very filled with...neon! I imagine its environment must be just as flashy as it is for it to have developed such colors. I wonder how flashy I might be, had I been raised somewhere even half as vibrant?',
    Color1: 'Light blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '温泉医生鱼',
    EnglishName: 'nibble fish',
    Sell: 1500,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2246,
    IconFilename: require('../../images/Fish/Fish67.png'),
    CritterpediaFilename: 'FishDokutaafish',
    FurnitureFilename: 'FtrFishDoctor',
    Description: 'Nibble fish are best known for their use in a certain skin treatment. This treatment has apparently been used for thousands of years. I have never experienced said treatment because they eat your dead skin with their little toothless mouths! Can you imagine anything so repellent?! Please don\'t ask me any follow-up questions. Hoo.',
    Color1: 'Brown',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '皇带鱼',
    EnglishName: 'oarfish',
    Sell: 9000,
    HHABasePoints: 71,
    Size: '3x2',
    InternalID: 2283,
    IconFilename: require('../../images/Fish/Fish69.png'),
    CritterpediaFilename: 'FishRyuuguunotukai',
    FurnitureFilename: 'FtrFishRyugu',
    Description: 'The oarfish is a long, eel-like fish that can supposedly reach up to 36 feet in length. They appear in various legends as things like messengers of the gods. It seems to me a creature like that could explain the myth of massive, ship-crushing sea serpents. It is, of course, well documented that people tend to exaggerate the size of "the one that got away".',
    Color1: 'Red',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '翻车鱼',
    EnglishName: 'ocean sunfish',
    Sell: 4000,
    HHABasePoints: 71,
    Size: '2x2',
    InternalID: 2278,
    IconFilename: require('../../images/Fish/Fish60.png'),
    CritterpediaFilename: 'FishManbou',
    FurnitureFilename: 'FtrFishManbou',
    Description: 'The ocean sunfish is a large relative of the blowfish with an unusual shape, like a fish head with a tail. They are a fairly relaxed species, often content to ride where the currents take them. This is fortunate as, otherwise, the sight of a large head coming toward you might be alarming!',
    Color1: 'Blue',
    Color2: 'Orange',
    route: 'Article1'
  },
  {
    Name: '比目鱼',
    EnglishName: 'olive flounder',
    Sell: 800,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2269,
    IconFilename: require('../../images/Fish/Fish51.png'),
    CritterpediaFilename: 'FishHirame',
    FurnitureFilename: 'FtrFishHirame',
    Description: 'Did you know that the olive flounder is the same shape as other fish when it hatches? But as it grows, it gets both wider and flatter, and can reach some three feet long. These flat fish spend much of their lives buried under the sandy ocean floor, waiting for prey to happen by. Imagine the surprise for said prey when they strike. It would be as if your kitchen floor were to bite you.',
    Color1: 'Beige',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '溪哥',
    EnglishName: 'pale chub',
    Sell: 200,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2216,
    IconFilename: require('../../images/Fish/Fish1.png'),
    CritterpediaFilename: 'FishOikawa',
    FurnitureFilename: 'FtrFishOikawa',
    Description: 'The pale chub is a river fish with simple back-and-silver coloring. Interestingly, the males\' coloring becomes most vibrant when he\'s trying to attract a mate! Though normally plain, these fellows really know how to look stylish when they want to. Perhaps I could learn a thing or two from the pale chub...',
    Color1: 'Blue',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '白斑狗鱼',
    EnglishName: 'pike',
    Sell: 1800,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2235,
    IconFilename: require('../../images/Fish/Fish20.png'),
    CritterpediaFilename: 'FishPaiku',
    FurnitureFilename: 'FtrFishPaiku',
    Description: 'The pike has always reminded me a bit of salmon, although a pike can grow rather larger. These brutes can grow to over four feet long, sometimes MUCH over! Hoo hoo! It is carnivorous and preys not only on other fish, but also mammals and some waterfowl. If I were to ever meet one in the water, I would have a most difficult time keeping my wits about me.',
    Color1: 'Green',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '食人鱼',
    EnglishName: 'piranha',
    Sell: 2500,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2249,
    IconFilename: require('../../images/Fish/Fish32.png'),
    CritterpediaFilename: 'FishPirania',
    FurnitureFilename: 'FtrFishPirania',
    Description: 'I am not exactly a fan of the piranha, despite knowing that they\'re mostly harmless. But those nasty, pointy teeth, Hoo. These infamous little blighters will attack when in groups. Imagine all of those hundreds of tiny teeth! To think that they\'re floundering about our peaceful waters, just waiting to strike. Well, never fear— I shall keep THIS one under the strictest lock and key, with nary a bathroom break allowed!',
    Color1: 'Green',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '西太公鱼',
    EnglishName: 'pond smelt',
    Sell: 400,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2236,
    IconFilename: require('../../images/Fish/Fish21.png'),
    CritterpediaFilename: 'FishWakasagi',
    FurnitureFilename: 'FtrFishWakasagi',
    Description: 'For many, thinking of pond smelt inevitably leads to thoughts of ice fishing in frozen rivers and lakes. Ice fishing involves making a round hole in the ice, dropping in your fishing line, and...waiting. Not to rain on anyone else\'s idea of fun, but...well, perhaps I shouldn\'t say anything.',
    Color1: 'Orange',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '龙睛金鱼',
    EnglishName: 'pop-eyed goldfish',
    Sell: 1300,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2221,
    IconFilename: require('../../images/Fish/Fish8.png'),
    CritterpediaFilename: 'FishDemekin',
    FurnitureFilename: 'FtrFishDemekin',
    Description: 'Pop-eyed goldfish have, as the name suggests, huge round eyes. But as babies they look like other goldfish! As they grow, their eyes begin to pop out and they gain their, hoo, distinct appearance... Imagine the poor fish fancier who unknowingly bought one! Their eyes might well pop out just as far!',
    Color1: 'Black',
    Color2: 'Light blue',
    route: 'Article1'
  },
  {
    Name: '刺豚',
    EnglishName: 'puffer fish',
    Sell: 250,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2263,
    IconFilename: require('../../images/Fish/Fish45.png'),
    CritterpediaFilename: 'FishHarisenbon',
    FurnitureFilename: 'FtrFishHarisenbon',
    Description: 'Like its cousin the blowfish, when the puffer fish feels threatened it inflates into a spiky balloon. The biggest difference between them is that the puffer fish is not deadly poisonous like its kin. So while it may look scary, the substantially reduced risk to life and limb makes it much better company.',
    Color1: 'Beige',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '彩虹鱼',
    EnglishName: 'rainbowfish',
    Sell: 800,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 4194,
    IconFilename: require('../../images/Fish/Fish80.png'),
    CritterpediaFilename: 'FishRainbowfish',
    FurnitureFilename: 'FtrFishRainbowfish',
    Description: 'The rainbowfish is a tropical fish known for its metallic colors and beautiful fins. There are over 50 different species, each unique and pleasing color. I must say, it does make me wish for feathers of a more exciting hue than "underbaked brownie."',
    Color1: 'Orange',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '兰寿金鱼',
    EnglishName: 'ranchu goldfish',
    Sell: 4500,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 5254,
    IconFilename: require('../../images/Fish/Fish85.png'),
    CritterpediaFilename: 'FishRanchu',
    FurnitureFilename: 'FtrFishRanchu',
    Description: 'The ranchu goldfish is a charming relative of the goldfish with a bumpy head and stout, round body. They have ordinary heads when born, but develop impressive rectangular heads after about three years. Supposedly their head shape changes depending on factors like the size of their tank... So ranchu goldfish enthusiasts aim to raise perfectly shaped specimens and work hard to achieve this. Of course, no one asks the ranchu goldfish themselves what shape they want their heads to be...',
    Color1: 'Red',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鳐鱼',
    EnglishName: 'ray',
    Sell: 3000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2277,
    IconFilename: require('../../images/Fish/Fish59.png'),
    CritterpediaFilename: 'FishEi',
    FurnitureFilename: 'FtrFishEi',
    Description: 'The ray is an unusually shaped fish with a flat body and a long body, somewhat related to sharks. Seen from the bottom, the mouth on its stomach appears to be smiling, which is objectively adorable. But be cautious—unlike most cute animals, some rays are extremely venomous. BEWARE THE SMILE.',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲷鱼',
    EnglishName: 'red snapper',
    Sell: 3000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2267,
    IconFilename: require('../../images/Fish/Fish49.png'),
    CritterpediaFilename: 'FishTai',
    FurnitureFilename: 'FtrFishTai',
    Description: 'Red snapper\' is the common name of dozens of fish species, and I wonder why it is so popular. Are there so many types of fish that are both a shade of red and have a tendency to snap? Were there no other names? What about \'burgundy biter\'? \'Garnet grasper\'? \'Puce pincher\'?',
    Color1: 'Red',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '五彩鳗',
    EnglishName: 'ribbon eel',
    Sell: 600,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2272,
    IconFilename: require('../../images/Fish/Fish71.png'),
    CritterpediaFilename: 'FishHanahigeutubo',
    FurnitureFilename: 'FtrFishHanahige',
    Description: 'The ribbon eel is related to the moray eel, though its bright coloration distinguishes it. It also has an unusual plant-like appendage at the tip of its nose that flutters as the creature moves. I like to think of it as having an extremely friendly nose that waves a greeting to those nearby!',
    Color1: 'Blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '恩氏多鳍鱼',
    EnglishName: 'saddled bichir',
    Sell: 4000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2254,
    IconFilename: require('../../images/Fish/Fish68.png'),
    CritterpediaFilename: 'FishEndorikerii',
    FurnitureFilename: 'FtrFishEndlicheri',
    Description: 'What an elegant specimen you\'ve found. The saddled bichir has a look entirely its own. They have poor eyesight, so they use their fine-tuned sniffers to seek out prey. Can you imagine relying solely on your sense of smell to find food? And if one nostril became clogged, would you be unable to tell how far away the scent was?',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲑鱼',
    EnglishName: 'salmon',
    Sell: 700,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2242,
    IconFilename: require('../../images/Fish/Fish27.png'),
    CritterpediaFilename: 'FishSake',
    FurnitureFilename: 'FtrFishSake',
    Description: 'Ah, salmon! Did you know their coloration is due specifically to their diet? Indeed, this is the case! The more they fill their diet with crustaceans such as krill and shrimp, the deeper shade of pink they are. If they ate a bushel of carrots, might they turn orange?',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '锯鲨',
    EnglishName: 'saw shark',
    Sell: 12000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2281,
    IconFilename: require('../../images/Fish/Fish74.png'),
    CritterpediaFilename: 'FishNokogirizame',
    FurnitureFilename: 'FtrFishNokogiri',
    Description: 'As you might expect from the name, the saw shark is a shark with a head that resembles a saw. This unusual appendage is used both to dig potential prey out of the sand and as a weapon against said prey. Given that, it seems like a more appropriate name would have been "shovel-sword shark," eh wot?',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲈鱼',
    EnglishName: 'sea bass',
    Sell: 400,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2266,
    IconFilename: require('../../images/Fish/Fish48.png'),
    CritterpediaFilename: 'FishSuzuki',
    FurnitureFilename: 'FtrFishSuzuki',
    Description: 'Sea bass is a name given to a variety of different species of saltwater fish. They are a varied bunch with some as small as four inches and some as staggeringly ginormous as eight feet! \'Sea bass\' is a bit pedestrian though. Many species have better names, such as \'redbanded perch.\' Or the delightfully whimsical dusky grouper! Or the potato cod! WILL NO ONE THINK OF THE PINK MAOMAO?!',
    Color1: 'Gray',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '海天使',
    EnglishName: 'sea butterfly',
    Sell: 1000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2255,
    IconFilename: require('../../images/Fish/Fish37.png'),
    CritterpediaFilename: 'FishKurione',
    FurnitureFilename: 'FtrFishKurione',
    Description: 'Such mystery! Such grace! Did you know that the sea butterfly\'s scientific name is Thecosomata? A very rough translation of that is \'shell body.\' Indeed, this illustrious creature is related to snails! However, it reminds me much more of an elegant feathered friend, the way it flies through the water. With such grace in flying, one shouldn\'t wonder if it\'s related to the owl, hoo hoo!',
    Color1: 'White',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '海马',
    EnglishName: 'sea horse',
    Sell: 1100,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2256,
    IconFilename: require('../../images/Fish/Fish39.png'),
    CritterpediaFilename: 'FishTatsunootoshigo',
    FurnitureFilename: 'FtrFishTatsunootoshigo',
    Description: 'Ah, a favorite of mine, to be sure! The sea horse is such a very unique creature and is indeed a fish! Though, as far as fish go, sea horses are not great swimmers. The sea horse, you see, has but a wee fin on its back, which propels it through water rather poorly. Thus these fish are often found using their prehensile tails to hold tight in amongst the sea grass. And here\'s one final fact for you... Sea horses have no stomach and so must constantly feed to stay alive! Indeed, the life of a land horse sounds far easier than that of the hardworking horse of the sea.',
    Color1: 'Orange',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '拟鳄龟',
    EnglishName: 'snapping turtle',
    Sell: 5000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 4192,
    IconFilename: require('../../images/Fish/Fish78.png'),
    CritterpediaFilename: 'FishKamitsukigame',
    FurnitureFilename: 'FtrFishKamitukigame',
    Description: 'The snapping turtle is a large turtle known for it\'s crocodile-like body and long claws. No, wait-- it is better known for it\'s ferocious bite, which it can deliver with shocking speed for a turtle. NO, WAIT-- it is BEST known for that time one chased me across a parking lot and I had to climb on top of a car.',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鳖',
    EnglishName: 'soft-shelled turtle',
    Sell: 3750,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2224,
    IconFilename: require('../../images/Fish/Fish65.png'),
    CritterpediaFilename: 'FishSuppon',
    FurnitureFilename: 'FtrFishSuppon',
    Description: 'These relatives of common turtles will not let go when they decide to bite down on something. Although they can be quite shy, they will become a bit aggressive when threatened. They are often found in water and are very good swimmers because of the flat shape of their shells. They swim with their snouts over the surface of the water so they can breathe. Soft-shelled turtles aren\'t safe to hold because they are so prone to biting at the slightest movement. However, if one bites down on you, it will usually let go when you put it safely back in the water.',
    Color1: 'Green',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鱿鱼',
    EnglishName: 'squid',
    Sell: 500,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2270,
    IconFilename: require('../../images/Fish/Fish52.png'),
    CritterpediaFilename: 'FishIka',
    FurnitureFilename: 'FtrFishIka',
    Description: 'Well, first off, squids are members of the mollusk family, just like the octopus. Many mollusks like snails and clams have shells, but the squid\'s body is almost completely soft. The exception is a long, narrow bit of hard material going through its main body - the last remnant of its shell. Of course, having your shell INSIDE is not a best practice. Perhaps they lost the owner\'s manual!',
    Color1: 'Beige',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '远东哲罗鱼',
    EnglishName: 'stringfish',
    Sell: 15000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2241,
    IconFilename: require('../../images/Fish/Fish26.png'),
    CritterpediaFilename: 'FishItou',
    FurnitureFilename: 'FtrFishItou',
    Description: 'The stringfish grows slowly, but also lives quite a long time for a fish, with up to 15 years being typical. Consequently, while it takes a while, they can get quite large-perhaps even up to six feet long! The stringfish is perhaps the best embodiment in the fish world of \'slow and steady wins the race\'',
    Color1: 'Brown',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲟鱼',
    EnglishName: 'sturgeon',
    Sell: 10000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 4189,
    IconFilename: require('../../images/Fish/Fish75.png'),
    CritterpediaFilename: 'FishTyouzame',
    FurnitureFilename: 'FtrFishTyouzame',
    Description: 'The sturgeon is a large and long-lived fish which has changed little in the last 300 million years. One curious behavior of theirs is leaping high out of the water and falling back in on their sides. The smacking sounds of their re-entry can be heard for up to half a mile away, likely more underwater! No one knows why they do it, but I like to think it\'s their impression of bread popping out of a toaster!',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '吸盘鱼',
    EnglishName: 'suckerfish',
    Sell: 1500,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 4203,
    IconFilename: require('../../images/Fish/Fish83.png'),
    CritterpediaFilename: 'FishKobanzame',
    FurnitureFilename: 'FtrFishKobanzame',
    Description: 'The suckerfish is a curious fish that likes to attach itself with its sucker mouth to larger marine animals. The benefit to the suckerfish is that it gets to eat smaller parasites and dead skin off the host\'s body. Amusingly, some people have used suckerfish on cords to catch large turtles with the fish\'s own suction! I imagine this practice is the cause of some awkward conversations between fish and turtle, eh wot',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '拟刺尾鲷',
    EnglishName: 'surgeonfish',
    Sell: 1000,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2258,
    IconFilename: require('../../images/Fish/Fish41.png'),
    CritterpediaFilename: 'FishNanyouhagi',
    FurnitureFilename: 'FtrFishNanyouhagi',
    Description: 'Hoo! Careful, now! These fish are particularly dangerous, despite their seemingly docile appearance. With its saturated blue and yellow tones, the surgeonfish is quite breathtaking. It\'s got to keep up with all the other vibrant fish that live in the coral too, I wager. Quite the competition! Its spine is sharp as a blade, so care must be taken when handling these beauties...',
    Color1: 'Blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '香鱼',
    EnglishName: 'sweetfish',
    Sell: 900,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2237,
    IconFilename: require('../../images/Fish/Fish22.png'),
    CritterpediaFilename: 'FishAyu',
    FurnitureFilename: 'FtrFishAyu',
    Description: 'Sweetfish are the damp heralds of summer! These slippery fellows appear in numbers when it warms up. They hatch in a river, then swim to the ocean. Once mature, they return to the river where they were born. But when they return depends on the river temperature— if it\'s too cold their fishing season will start later. Some even say summer can\'t start without sweetfish despite the KEY role played by the earth\'s axial tilt!',
    Color1: 'Green',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '蝌蚪',
    EnglishName: 'tadpole',
    Sell: 100,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2225,
    IconFilename: require('../../images/Fish/Fish64.png'),
    CritterpediaFilename: 'FishOtamajakusi',
    FurnitureFilename: 'FtrFishOtama',
    Description: 'Undoubtedly you know that tadpoles eventually turn into frogs. I must say, I find them impossibly adorable with their squiggly little tails. But even cuter... when they sprout legs! Why, we can witness accelerated evolution in these squirmy little ones. Hoo, it makes me so emotional!',
    Color1: 'Black',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '吴郭鱼',
    EnglishName: 'tilapia',
    Sell: 800,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 4190,
    IconFilename: require('../../images/Fish/Fish76.png'),
    CritterpediaFilename: 'FishThirapia',
    FurnitureFilename: 'FtrFishThirapia',
    Description: 'Wherever the waters are warm, the tilapia can be found. It is a highly adaptable river fish. They mainly feed on algae, but they will also eat larvae and dead fish— or whatever fits in their mouths. I will confess that, as a growing owlet, I similarly defined food as \'anything that fits in my beak.\'',
    Color1: 'Black',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲔鱼',
    EnglishName: 'tuna',
    Sell: 7000,
    HHABasePoints: 71,
    Size: '2x1',
    InternalID: 2274,
    IconFilename: require('../../images/Fish/Fish57.png'),
    CritterpediaFilename: 'FishMaguro',
    FurnitureFilename: 'FtrFishMaguro',
    Description: 'The tuna is a large ocean fish that can reach upwards of nine feet long. Besides its great size, it\'s notable for continuing to swim even when it\'s sleeping! Well, to be fair, if it doesn\'t keep swimming, it won\'t be able to breathe and will of course die... But sleep should be restful, eh wot! If I were the tuna I would feel very hard done by!',
    Color1: 'Blue',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '鲸鲨',
    EnglishName: 'whale shark',
    Sell: 13000,
    HHABasePoints: 71,
    Size: '3x2',
    InternalID: 2282,
    IconFilename: require('../../images/Fish/Fish72.png'),
    CritterpediaFilename: 'FishJinbeezame',
    FurnitureFilename: 'FtrFishJinbee',
    Description: 'The mighty whale shark is the largest species of fish in the world with specimens up to 60 feet long! Unlike many of their kin in the shark family, whale sharks are nonviolent, eating only plankton and such. They grow slowly and live long, relaxed lives of filter feeding and leisure in warm waters. So if you ever have to choose a fish as a roommate, you could do worse than the whale shark. Unless you can\'t swim.',
    Color1: 'Black',
    Color2: 'Blue',
    route: 'Article1'
  },
  {
    Name: '黄鲈鱼',
    EnglishName: 'yellow perch',
    Sell: 300,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2233,
    IconFilename: require('../../images/Fish/Fish18.png'),
    CritterpediaFilename: 'FishYellowparch',
    FurnitureFilename: 'FtrFishYellowparch',
    Description: 'The yellow perch is certainly worth squawking about. I find it a sight to behold! That jagged dorsal fin! Those brilliant stripes! Those glorious colours! Hoo, truly it is quite the specimen. I would be thrilled to witness it firsthand in its natural environment... But the yellow perch\'s peak season is winter, I\'m afraid. (So very afraid... of winter\'s biting chill...)',
    Color1: 'Yellow',
    Color2: 'Black',
    route: 'Article1'
  },
  {
    Name: '狮子鱼',
    EnglishName: 'zebra turkeyfish',
    Sell: 500,
    HHABasePoints: 71,
    Size: '1x1',
    InternalID: 2261,
    IconFilename: require('../../images/Fish/Fish44.png'),
    CritterpediaFilename: 'FishMinokasago',
    FurnitureFilename: 'FtrFishMinokasago',
    Description: 'The sheer brilliance and diversity found in the aquatic underworld never cease to amaze me. This zebra turkeyfish is as stunning to gaze upon as it is deadly. Those spines that are part of its defining physique are chock-full of venom. Fortunately, zebra turkeyfish are not susceptible to another\'s venom. Though solitary, I imagine they give one another a mean fin bump when passing each other by.',
    Color1: 'Red',
    Color2: 'Black',
    route: 'Article1'
  }
];
